---
# Begin list of tasks

# References variables definied in roles/optimize/vars/main.yml
- name: "Creates an {{ swapfile_size_GB }} GB swapfile"
  command: "fallocate -l {{ swapfile_size_GB }}G {{ swapfile_path }} creates={{ swapfile_path }}"

- name: Changes the permissions on newly created swapfile
  file: "path={{ swapfile_path }} mode=600"

- name: Sets the swap headers
  command: "mkswap {{ swapfile_path }} creates={{ swapfile_path }}"

- name: Adds the swapfile on to the system
  command: "swapon {{ swapfile_path }} creates={{ swapfile_path }}"

- name: Permanently activates swapfile by mounting it to /etc/fstab
  mount: "name=none src={{ swapfile_path }} fstype=swap opts=sw passno=0 dump=0 state=present"

- name: "Changes swappiness value to {{ swappiness_value }}"
  command: "sysctl vm.swappiness={{ swapiness_value }}"

- name: "Permanently changes swappiness value to {{ swappiness_value }} in /etc/sysctl.conf"
  lineinfile: dest=/etc/sysctl.conf state=present regexp=^vm.swappiness= line=vm.swappiness={{ swapiness_value }}

- name: "Changes VFS cache pressure to {{ swap_cache_pressure }}"
  command: "sysctl vm.vfs_cache_pressure={{ swap_cache_pressure }}"

- name: "Permanently changes VFS cache pressure to {{ swap_cache_pressure }} in /etc/sysctl.conf"
  lineinfile: dest=/etc/sysctl.conf state=present regexp=^vm.vfs_cache_pressure= line=vm.vfs_cache_pressure={{ swap_cache_pressure }}
