---
# Highest level ansible playbook file.
# Note to self: Ansible playbooks use YAML, which is organized like lists.
- name: Main Orchestrate Ansible Playbook
  hosts: deployment_local
  remote_user: peterpacz1
  sudo: yes

# Uses roles (playbooks inside the role/common)
  roles:
   # Installs the most basic of dependencies
   - common
   # Adds swap, and conducts various subtle optimizations
   - optimization
   # Configures IPtables, SSH daemon, and rkhunter
   - security
