---
# List of tasks to execute

- name: Install fail2ban on to server
  apt: pkg=fail2ban state=installed

- name: Copy fail2ban configuration file on to server
  template: "src=jail.local.j2 dest={{ fail2ban_config_location }}" "
  notify:
    - restart fail2ban
