---
# Begin list of vars

# SSH configuration (used in templates/sshd_config.j2)
ssh_port: 22
ssh_sshd_config_location: /etc/ssh/sshd_config

# SSH Authentication settings
ssh_PermitRootLogin: "no"
ssh_PasswordAuthentication: "no"
ssh_AllowGroups: sudo
