---
# Begin lists of tasks

# The same as apt-get update && apt-get upgrade
- name: Update server software
  apt: update_cache=yes #upgrade=dist

  # Installs multiple packages at the same time
- name: Install dependencies
  apt: pkg={{item}} state=installed
  with_items:
    - screen
    - git
